name: Doc
on:
  push:
    branches:
      - master
jobs:
  doc-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build
      run: npm install && npm run doc

    - name: Submit3
      uses: ad-m/github-push-action@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
