name: Doc
on:
  push:
    branches:
      - master
jobs:
  doc-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build
      run: npm install && npm run doc

    - name: Submit3
      uses: ludeeus/action-push@master
      secrets: ${{ secrets.ACCESS_TOKEN }}
      env: 
        ACTION_MAIL: 771565119@qq.com
        ACTION_NAME: ounana
        ACTION_BRANCH: master
        ACTION_MESSAGE: doc is ok
