name: Doc
on:
  push:
    branches:
      - master
jobs:
  doc-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build
      uses: ./.github/action-a
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs
        BUILD_SCRIPT: npm install && npm run doc
