name: NICEST
on:
  push:
    branches:
      - master
jobs:
  DOC-DEPLOY:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Run build
      uses: ./.github/action-deploy-doc
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs
        BUILD_SCRIPT: npm install && npm run doc
