name: deploy-doc
on:
  push:
    branches:
      - master
jobs:
  DOC-DEPLOY:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      uses: ./.github/my-action
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs
        BASE_BRANCH: master
